FROM node:12-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 3000
#ARG NODE_ENV=production
#ARG SECRET=secret
#ARG MADE_WITH=love
#ARG MONGODB_URI=mongodb://192.168.100.6:27017
CMD [ "npm", "start" ]
